services:
  redis:
    extends:
      file: ./docker/redis.yml
      service: redis
    networks:
      - larity-network

  rabbitmq:
    extends:
      file: ./docker/rabbitmq.yml
      service: rabbitmq
    networks:
      - larity-network

  postgres:
    extends:
      file: ./docker/postgres.yml
      service: postgres
    networks:
      - larity-network

volumes:
  postgres_data:
  rabbitmq_data:
  redis_data:

networks:
  larity-network:
    name: larity-network
