// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { config } from 'dotenv';
import path from 'path';
import { defineConfig } from 'prisma/config';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

config({ path: path.resolve(__dirname, '.env') }); // loads .env
config({ path: path.resolve(__dirname, '.env.development') }); // loads .env.development if it exists

export default defineConfig({
  schema: './packages/infra/prisma/schema.prisma',
  migrations: {
    path: './packages/infra/prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
