import { AIBriefGeneratorService } from "meeting-mode";
import { prisma } from "../lib/prisma";

export const MeetingBriefService = {
  async generateBrief(meetingId: string) {
    const meeting = await prisma.meeting.findUnique({
      where: { id: meetingId },
      select: { preMeetingBrief: true },
    });

    if (!meeting) {
      throw new Error("Meeting not found");
    }

    if (meeting.preMeetingBrief) {
      // It was pre-generated by the background job
      return meeting.preMeetingBrief;
    }

    // Fallback: Generate on the fly (e.g. for ad-hoc meetings where the cron hasn't run)
    const newBrief =
      await AIBriefGeneratorService.generateAndSaveBrief(meetingId);
    return newBrief;
  },
};
